[package]
# This is the vmware-k8s-1.27 variant. "." is not allowed in crate names, but
# we don't use this crate name anywhere.
name = "vmware-k8s-1_27"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[package.metadata.build-variant.image-layout]
partition-plan = "unified"

[package.metadata.build-variant.image-features]
grub-set-private-var = true

[package.metadata.build-variant]
image-format = "vmdk"
supported-arches = ["x86_64"]
kernel-parameters = [
    "console=tty1",
    # Only reserve if there are at least 2GB
    "crashkernel=2G-:256M",
    "net.ifnames=0",
    "netdog.default-interface=eth0:dhcp4,dhcp6?",
    "quiet",
]
included-packages = [
    "cni",
    "cni-plugins",
    "kernel-6.1",
    "kubelet-1.27",
    "open-vm-tools",
    "release",
]

[lib]
path = "../variants.rs"

[build-dependencies]
settings-defaults = { path = "../../packages/settings-defaults" }
settings-plugins = { path = "../../packages/settings-plugins" }
settings-migrations = { path = "../../packages/settings-migrations" }
