schema-version = 1
release-version = "1.24.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.45.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "2.8.1"
vendor = "bottlerocket"
