[package]
name = "settings-plugin-aws-ecs-2"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false

[lib]
crate-type = ["cdylib"]
name = "settings_aws_ecs_2"

[dependencies]
abi_stable = "0.11.3"
serde = "1.0.198"
serde_json = "1.0.116"

# settings plugins
bottlerocket-settings-models.workspace = true
bottlerocket-settings-plugin.workspace = true
