[package]
name = "schnauzer"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[features]
default = []
testfakes = []

[dependencies]
apiclient.workspace = true
argh.workspace = true
async-trait.workspace = true
base64.workspace = true
bottlerocket-modeled-types.workspace = true
cached = { workspace = true, features = ["async"] }
constants.workspace = true
bottlerocket-release.workspace = true
dns-lookup.workspace = true
handlebars.workspace = true
http.workspace = true
lazy_static.workspace = true
log.workspace = true
maplit.workspace = true
models.workspace = true
num_cpus.workspace = true
percent-encoding.workspace = true
pest.workspace = true
pest_derive.workspace = true
regex.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_plain.workspace = true
settings-extension-oci-defaults.workspace = true
simplelog.workspace = true
snafu.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] } # LTS
toml.workspace = true
url.workspace = true

[dev-dependencies]
# Workaround to enable a feature during integration tests.
schnauzer = { workspace = true, features = ["testfakes"] }

[build-dependencies]
generate-readme.workspace = true
