[package]
name = "docker-cli"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/docker/cli/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/docker/cli/archive/v25.0.5/cli-25.0.5.tar.gz"
sha512 = "39f49514605a3c78661f105094f9c28beb01927a2d7dc474048c2a27135ca8c3f075a6f05157a176c032d5e7c105f00c9100c15713298b33bd34a6f399bac84d"

[build-dependencies]
glibc = { path = "../glibc" }
