[package]
name = "containerd"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/containerd/containerd/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/containerd/containerd/archive/v1.6.34/containerd-1.6.34.tar.gz"
sha512 = "4adbdd7cfaf387fa1d3fe1f5150819fd9232e9e7cdb07777068aa5bf050145ad24b4076860ef36ebb410e7019ff2cee529f1563517064f272dc8fb0261316179"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
runc = { path = "../runc" }
pigz = { path = "../pigz" }
