[package]
name = "add-hostname-override-source"
version = "0.1.0"
authors = ["Todd Neal <tnealt@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false

[dependencies]
migration-helpers.workspace = true
