name: Build
on:
  pull_request:
    branches: [develop]
    # Here we list file types that don't affect the build and don't need to use
    # up our Actions runners.
    paths-ignore:
      # draw.io (diagrams.net) files, the source of png images for docs
      - '**.drawio'
      # Example configuration files
      - '**.example'
      # Markdown documentation
      - '**.md'
      # Images for documentation
      - '**.png'
      # Templates for README files
      - '**.tpl'
      # Sample config files and OpenAPI docs
      - '**.yaml'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'bottlerocket-os/bottlerocket'
    runs-on:
      group: bottlerocket
      labels: bottlerocket_ubuntu-latest_32-core
    continue-on-error: true
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    name: "Build ${{ matrix.arch }}"
    steps:
      - name: Random delay
        run: |
          delay=$((1 + $RANDOM % 32))
          echo "Waiting ${delay} seconds before execution"
          sleep $delay
      - uses: actions/checkout@v4
      - name: Preflight step to set up the runner
        uses: ./.github/actions/setup-node
      - run: rustup component add rustfmt
      - run: cargo make unit-tests
      - run: cargo make check-fmt
      - run: cargo make check-clippy
      - run: cargo make check-shell
      - run: |
          cargo make \
            -e BUILDSYS_ARCH=${{ matrix.arch }} \
            -e BUILDSYS_JOBS=12 \
            build-all
